### ISSUE TITLE
Can't find report file...

### ISSUE THREAD

**Issue by lanecm** [ivanklee86/xunit-slack-reporter#113]
Hello...

We're getting the following error from `xunit-slack-reporter`:

```
Traceback (most recent call last):
  File "/source/app/script.py", line 23, in main
    xunit_report = xunit_utils.read_xunit(pathlib.Path(xunit_path))
  File "/source/app/utils/xunit_utils.py", line 6, in read_xunit
    return JUnitXml.fromfile(xunit_report_path)
  File "/usr/local/lib/python3.7/site-packages/junitparser/junitparser.py", line 283, in fromfile
    tree = etree.parse(filepath)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '***/target/failsafe-reports/failsafe-summary.xml'
```

However, we confirm the file exists right before we run `xunit-slack-reporter`:

```
      - name: Output Test Report
        run: |
          cat ***/target/failsafe-reports/failsafe-summary.xml

      - name: xUnit Slack Reporter
        uses: ivanklee86/xunit-slack-reporter@v1.0.1
        env:
          SLACK_CHANNEL: ***
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          XUNIT_PATH: ***/target/failsafe-reports/failsafe-summary.xml
```

The "Output Test Report" step echoes the contents of the file, so we know it's there. Any ideas?

**Comment by rcubillo** [comment]
Hey,  were you able to fix this?  @lanecm  @ivanklee86

**Comment by ivanklee86** [comment]
@rcubillo I haven't had a chance to look at this codebase for a while.  I'm doing some cleanup/modernization and will try and take a peek at this report after that. :)

**Comment by rcubillo** [comment]
Thank you @ivanklee86

**Comment by ivanklee86** [comment]
`v1.3.0` (just on the marketplace) should support file globs now in the `XUNIT_GLOB` env var. :) Please give it a shot!

**Comment by rcubillo** [comment]
Thank you so much. I don't get any error anymore, but it's not importing anything into slack :(

**Comment by ivanklee86** [comment]
[This](https://argocd-notifications.readthedocs.io/en/stable/services/slack/) website has a great step-by-step on how to set up a notification bot.  Would you mind checking to make sure your bot is set up in a similar way (or better yet use a new app) and open a separate ticket if you're still having issues?  Thank you!
