### ISSUE TITLE
Action not publishing the junit.xml results into slack.

### ISSUE THREAD

**Issue by rcubillo** [ivanklee86/xunit-slack-reporter#182]
I configured my slack bot using this guide : https://argocd-notifications.readthedocs.io/en/stable/services/slack/ . I have my bot in the channel and I have the correct keys under secrets. I ran the action, but I'm still not able to publish the results into slack
<img width="1696" alt="Screen Shot 2022-01-10 at 10 17 39 AM" src="https://user-images.githubusercontent.com/29494434/148800070-260ed274-65ac-4881-a59b-44a21a2d2be0.png">
<img width="1687" alt="Screen Shot 2022-01-10 at 10 19 11 AM" src="https://user-images.githubusercontent.com/29494434/148800173-43c997b3-1ebc-4382-8020-aa619ffa938d.png">
 I'm not getting any errors. Any ideas of what I'm missing?

**Comment by rcubillo** [comment]
Quick update:

 If I add the .xml file into the root folder, and the `XUNIT_GLOB: "**/*.xml"` tt works.  I'm storing the the xml in /home/runner/junit.xml location. Now, if I remove the xml from the root and I add  ` XUNIT_GLOB: /home/runner/junit.xml` I get _NotImplementedError: Non-relative patterns are unsupported error message

**Comment by ivanklee86** [comment]
If you'd like to access a fixed path, it should go in the `XUNIT_PATH` environment variable.  (Pathlib draws a distinction between specifying a path and searching for matching files. :) )

**Comment by rcubillo** [comment]
It seems like the docker won't be able to access that hosted runner. Please let me know if you can look into it. If not, I will find another way to do it. Thank you.
